CREATE TABLE AUTOMOVEL (
  PLACA VARCHAR2(10) NOT NULL,
  ANO NUMBER(4) NOT NULL,
  MODELO VARCHAR2(20) NOT NULL,
  MOTORIZACAO NUMBER(2, 1) NOT NULL,
  SERVICO_ID_SERVICO NUMBER(10) NOT NULL
);

ALTER TABLE AUTOMOVEL ADD CONSTRAINT AUTOMOVEL_PK PRIMARY KEY (PLACA);

CREATE TABLE CLIENTE (
  CPF VARCHAR2(11) NOT NULL,
  NOME VARCHAR2(20) NOT NULL,
  TEL_CLIENTE VARCHAR2(15),
  EMAIL_CLIENTE VARCHAR2(30),
  AUTOMOVEL_PLACA VARCHAR2(10) NOT NULL,
  ENDERECO_ENDERECO_ID NUMBER NOT NULL
);

ALTER TABLE CLIENTE ADD CONSTRAINT CLIENTE_PK PRIMARY KEY (CPF);

ALTER TABLE CLIENTE ADD CONSTRAINT UK_EMAIL_CLIENTE UNIQUE (EMAIL_CLIENTE);

CREATE TABLE ENDERECO (
  CIDADE VARCHAR2(20) NOT NULL,
  UF VARCHAR2(2) NOT NULL,
  CEP VARCHAR2(15) NOT NULL,
  RUA VARCHAR2(50) NOT NULL,
  NUMERO VARCHAR2(5),
  COMPLEMENTO VARCHAR2(20),
  ENDERECO_ID NUMBER NOT NULL
);

ALTER TABLE ENDERECO ADD CONSTRAINT ENDERECO_PK PRIMARY KEY (ENDERECO_ID);

CREATE TABLE FORNECEDOR (
  CNPJ VARCHAR2(20) NOT NULL,
  TEL_FORNECEDOR VARCHAR2(15),
  EMAIL_FORNECEDOR VARCHAR2(30),
  PRODUTO_COD_PRODUTO NUMBER(20) NOT NULL,
  ENDERECO_ENDERECO_ID NUMBER NOT NULL
);

ALTER TABLE FORNECEDOR ADD CONSTRAINT FORNECEDOR_PK PRIMARY KEY (CNPJ);

ALTER TABLE FORNECEDOR ADD CONSTRAINT UK_EMAIL_FORNECEDOR UNIQUE (EMAIL_FORNECEDOR);

CREATE TABLE MONTADORA (
  ID_MONTADORA NUMBER(5) NOT NULL,
  CNPJ VARCHAR2(20) NOT NULL,
  NOME VARCHAR2(20) NOT NULL,
  AUTOMOVEL_PLACA VARCHAR2(10) NOT NULL
);

ALTER TABLE MONTADORA ADD CONSTRAINT MONTADORA_PK PRIMARY KEY (ID_MONTADORA);

ALTER TABLE MONTADORA ADD CONSTRAINT UK_CNPJ_MONTADORA UNIQUE (CNPJ);

CREATE TABLE OFICINA (
  CNPJ VARCHAR2(20) NOT NULL,
  NOME_FANTASIA VARCHAR2(25) NOT NULL,
  TIPO VARCHAR2(20) NOT NULL,
  ENDERECO_ENDERECO_ID NUMBER NOT NULL
);

ALTER TABLE OFICINA ADD CONSTRAINT OFICINA_PK PRIMARY KEY (CNPJ);

CREATE TABLE PRODUTO (
  COD_PRODUTO NUMBER(20) NOT NULL,
  MARCA VARCHAR2(20) NOT NULL,
  TIPO VARCHAR2(20) NOT NULL,
  NOME VARCHAR2(20) NOT NULL,
  VALOR_PRODUTO NUMBER(12, 2) NOT NULL
);

ALTER TABLE PRODUTO ADD CONSTRAINT PRODUTO_PK PRIMARY KEY (COD_PRODUTO);

CREATE TABLE SERVICO (
  ID_SERVICO NUMBER(10) NOT NULL,
  TIPO_SERVICO VARCHAR2(30) NOT NULL,
  DURACAO VARCHAR2(15) NOT NULL,
  DELIVERY CHAR(1),
  OFICINA_CNPJ VARCHAR2(20) NOT NULL
);

ALTER TABLE SERVICO ADD CONSTRAINT SERVICO_PK PRIMARY KEY (ID_SERVICO);

CREATE TABLE UTILIZA (
  SERVICO_ID_SERVICO NUMBER(10) NOT NULL,
  PRODUTO_COD_PRODUTO NUMBER(20) NOT NULL
);

ALTER TABLE UTILIZA ADD CONSTRAINT UTILIZA_PK PRIMARY KEY (SERVICO_ID_SERVICO, PRODUTO_COD_PRODUTO);

ALTER TABLE AUTOMOVEL
  ADD CONSTRAINT AUTOMOVEL_SERVICO_FK FOREIGN KEY (SERVICO_ID_SERVICO)
  REFERENCES SERVICO (ID_SERVICO);

ALTER TABLE CLIENTE
  ADD CONSTRAINT CLIENTE_AUTOMOVEL_FK FOREIGN KEY (AUTOMOVEL_PLACA)
  REFERENCES AUTOMOVEL (PLACA);

ALTER TABLE CLIENTE
  ADD CONSTRAINT CLIENTE_ENDERECO_FK FOREIGN KEY (ENDERECO_ENDERECO_ID)
  REFERENCES ENDERECO (ENDERECO_ID);

ALTER TABLE FORNECEDOR
  ADD CONSTRAINT FORNECEDOR_ENDERECO_FK FOREIGN KEY (ENDERECO_ENDERECO_ID)
  REFERENCES ENDERECO (ENDERECO_ID);

ALTER TABLE FORNECEDOR
  ADD CONSTRAINT FORNECEDOR_PRODUTO_FK FOREIGN KEY (PRODUTO_COD_PRODUTO)
  REFERENCES PRODUTO (COD_PRODUTO);

ALTER TABLE MONTADORA
  ADD CONSTRAINT MONTADORA_AUTOMOVEL_FK FOREIGN KEY (AUTOMOVEL_PLACA)
  REFERENCES AUTOMOVEL (PLACA);

ALTER TABLE OFICINA
  ADD CONSTRAINT OFICINA_ENDERECO_FK FOREIGN KEY (ENDERECO_ENDERECO_ID)
  REFERENCES ENDERECO (ENDERECO_ID);

ALTER TABLE SERVICO
  ADD CONSTRAINT SERVICO_OFICINA_FK FOREIGN KEY (OFICINA_CNPJ)
  REFERENCES OFICINA (CNPJ);

ALTER TABLE UTILIZA
  ADD CONSTRAINT UTILIZA_PRODUTO_FK FOREIGN KEY (PRODUTO_COD_PRODUTO)
  REFERENCES PRODUTO (COD_PRODUTO);

ALTER TABLE UTILIZA
  ADD CONSTRAINT UTILIZA_SERVICO_FK FOREIGN KEY (SERVICO_ID_SERVICO)
  REFERENCES SERVICO (ID_SERVICO);